### ISSUE TITLE
bug: deno.land/x/semver-cli is no longer accessible

### ISSUE THREAD

**Issue by shivajivarma** [Optum/semver-cli#28]
## Bug Report

 deno.land/x/semver-cli is no longer published, as documented in the installation steps.

**Comment by justinmchase** [comment]
@shivajivarma Thanks for the report its back now here:

https://deno.land/x/semver_cli

I'm not sure how it happened but the webhook got deleted and I guess deno will expire a module if its disconnected for too long.

**Comment by justinmchase** [comment]
I also updated the url in the main readme, thanks again.

**Comment by justinmchase** [comment]
Fixed by #34
